### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by Niklas-Peter** [tibbe/hyena#1]
In which status is this project?
I think it is not suited for production, but is it working and can serve as source for learning concepts for creating a HTTP server in Haskell? Of course, there are many other up to date implementations like warp, happstack, snap, mighttpd and second-transfer, but they are much more complex and still harder to understand for beginners.

**Comment by tibbe** [comment]
Hi!

This project is essentially abandoned. If you can learn something from the source code (which is one of the first uses of "iteratees/enumerators" in Haskell), that's great.

**Comment by Niklas-Peter** [comment]
Thanks for your reply!

I tried `cabal install hyena`, but it ends with the following message. 
I searched for a solution:
- Removed all installed packages.
- Created a sandbox.

That did not help. It seems as if hyena requires older packages. However I expect, that it worked some years ago, so cabal should be able to find those old versions of the packaes or?

I tried it on Windows 7. Your source code's headers sometimes include "not portable", but in the .cabal file there is a condition for Windows and not Windows, so I expect, that it should run on Windows or which OS is supported?

If you know a solution, please let me know:

```
cabal update 
cabal install hyena
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hyena-0.1.0.1 (user goal)
next goal: network (dependency of hyena-0.1.0.1)
rejecting: network-2.6.2.1/installed-e84..., 2.6.2.1, 2.6.2.0, 2.6.1.0,
2.6.0.2, 2.6.0.1, 2.6.0.0, 2.5.0.0, 2.4.2.3, 2.4.2.2, 2.4.2.1, 2.4.2.0,
2.4.1.2, 2.4.1.1, 2.4.1.0, 2.4.0.1, 2.4.0.0, 2.3.2.0, 2.3.1.1, 2.3.1.0,
2.3.0.14, 2.3.0.13, 2.3.0.12, 2.3.0.11, 2.3.0.10, 2.3.0.9, 2.3.0.8, 2.3.0.7,
2.3.0.6, 2.3.0.5, 2.3.0.4, 2.3.0.3, 2.3.0.2, 2.3.0.1, 2.3 (conflict: hyena =>
network>=2.1 && <2.3)
trying: network-2.2.3.1
next goal: parsec (dependency of network-2.2.3.1)
rejecting: parsec-3.1.9/installed-268... (conflict: parsec =>
mtl==2.2.1/installed-e69..., hyena => mtl>=1 && <2.0.2)
trying: parsec-3.1.9
trying: text-1.2.1.3/installed-4a0... (dependency of parsec-3.1.9)
next goal: binary (dependency of text-1.2.1.3/installed-4a0...)
rejecting: binary-0.7.5.0/installed-c94... (conflict: binary =>
containers==0.5.6.2/installed-e8a..., hyena => containers>=0.3 && <0.4)
rejecting: binary-0.8.2.1, 0.8.2.0, 0.8.1.0, 0.8.0.1, 0.8.0.0, 0.7.6.1,
0.7.6.0, 0.7.5.0, 0.7.4.0, 0.7.3.0, 0.7.2.3, 0.7.2.2, 0.7.2.1, 0.7.2.0,
0.7.1.0, 0.7.0.1, 0.7.0.0, 0.6.4.0, 0.6.3.0, 0.6.2.0, 0.6.1.0, 0.6.0.0,
0.5.1.1, 0.5.1.0, 0.5.0.2, 0.5.0.1, 0.5, 0.4.5, 0.4.4, 0.4.3.1, 0.4.3, 0.4.2,
0.4.1, 0.4, 0.3, 0.2 (conflict: text => binary==0.7.5.0/installed-c94...)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```
